services:
  cleo:
    container_name: cleo-app
    image: cleo-agent:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        SUPABASE_SERVICE_ROLE: ${SUPABASE_SERVICE_ROLE}
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
        GOOGLE_GENERATIVE_AI_API_KEY: ${GOOGLE_GENERATIVE_AI_API_KEY}
        MISTRAL_API_KEY: ${MISTRAL_API_KEY}
        XAI_API_KEY: ${XAI_API_KEY}
        PERPLEXITY_API_KEY: ${PERPLEXITY_API_KEY}
        OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
        CSRF_SECRET: ${CSRF_SECRET}
    ports:
      - "3000:3000"
    env_file:
      - ./.env.local
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped 