services:
  cleo:
    container_name: cleo-app
    image: cleo-agent:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env.local
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped 